from lncrnapy.train.classification import train_classifier
from lncrnapy.train.masked_token_modeling import train_masked_token_modeling
from lncrnapy.train.masked_motif_modeling import train_masked_motif_modeling
from lncrnapy.train.regression import train_regressor